apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: s08zi8050-nodejs-gitops
  description: This is GitOps manifest for s08zi8050-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=s08zi8050-nodejs
    backstage.io/kubernetes-id: s08zi8050-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: s08zi8050-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:s08zi8050-nodejs
